spring.application.name=petshop-api

# ── H2 Console ────────────────────────────────────────────────────────────────
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=false

# ── Datasource ────────────────────────────────────────────────────────────────
spring.datasource.url=jdbc:h2:mem:petshopdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ── JPA ───────────────────────────────────────────────────────────────────────
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ── Swagger / OpenAPI ─────────────────────────────────────────────────────────
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.api-docs.path=/v3/api-docs

# ── HATEOAS ───────────────────────────────────────────────────────────────────
spring.hateoas.use-hal-as-default-json-media-type=true

# ── Tratamento de rotas inexistentes ──────────────────────────────────────────
# Necessário para que NoHandlerFoundException seja lançada e tratada no handler
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
